name: Reuse other workflow
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: MyReusingWorld

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@meMEMEEE!'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]    
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
